### ISSUE TITLE
Debug Issue 90

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-times-tools#20]
https://blog.emberjs.com/2019/03/22/the-ember-times-issue-90.html

oddities:
- single ticks
- triple ticks
- code markdown within quotes / italices
- double curlies, maybe if bold or in titles, has issues

**Comment by amyrlam** [comment]
Goodbits doesn't take single tick or backtick and we put those in italices manually, found https://blog.emberjs.com/2018/04/20/the-emberjs-times-issue-43.html as example

**Comment by tylerturdenpants** [comment]
Got it!  Will look at it this weekend.

**Comment by tylerturdenpants** [comment]
Just leaving this as a note:
I think the fix for some of these things is to insert html using the trix editor api instead of updating the the element value.
